name: Release

on:
    push:
        branches:
            - master
jobs:

    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Configure NodeJs
                uses: actions/setup-node@v2
                with:
                    node-version: 16
                    registry-url: https://npm.pkg.github.com/
                    scope: '@eduardoperez2151'
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            -   name: Install Dependencies
                run: npm ci
            -   name: Linting
                run: npm run lint
            -   name: Testing
                run: npm test
            -   name: Building
                run: npm run build
            -   name: Generating docs
                run: npm run compodoc
            -   name: Commiting docs changes
                uses: EndBug/add-and-commit@v7
                with:
                    author_name: CI
                    author_email: eduardo.perez.2151@gmail.com.uy
                    message: 'docs(compodoc): generate new doc version'
                    add: './docs'
                    push: false
            -   name: Push docs to protected branch
                uses: CasperWA/push-protected@v2
                with:
                    token: ${{ secrets.NPM_TOKEN }}
                    branch: master
                    unprotect_reviews: true
            -   name: Releasing
                uses: cycjimmy/semantic-release-action@v2
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            -   name: Publishing docs
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./docs
